print("Sequence type")
Ias_members = ["Agateeswaran", "Boomika", "Balaji", "Devi Darshana", "Darshan", "Dharun", "Gopinath",
               "Jai prasanth", "Intharesh", "Sanjay", "Shathiya sri", "Selva Bharathi", "Sibi", "Vibushana"]
java_members=["Naveen","Rishi","Sudharsan"]
# List type
print("List type")
print(Ias_members)
print(type(Ias_members))
for i in range(len(Ias_members)):
    print(i+1, ":", Ias_members[i])
print(Ias_members.count("Sanjay"))
print(Ias_members.index("Sanjay"))
Ias_members.reverse()
print(Ias_members)
Ias_members.sort()
print(Ias_members)
Ias_members.append('Ajay')
print(Ias_members)
Ias_members.pop()
print(Ias_members)
Ias_members.insert(2,'Ajay')
print("After inserting Ajat to Ias members:\n\t",Ias_members)
Ias_members.extend(java_members)
print("After Extending Ias members with Java members:\n\t",Ias_members)
r1=Ias_members.index("Naveen")
print("Index of Naveen:",r1)
r2=Ias_members.index("Rishi")
print("Index of Rishi:",r2)
r3=Ias_members.index("Sudharsan")
print("Index of Sudharsan:",r3)
Ias_members.remove(Ias_members[r1])
print("After imnplementing first remove:\n\t",Ias_members)
Ias_members.remove(Ias_members[r2-1])
print("After imnplementing Second remove:\n\t",Ias_members)
Ias_members.remove(Ias_members[r3-2])
print("After imnplementing third remove:\n\t",Ias_members)
print(Ias_members[3:7])
java_members = Ias_members.copy()
print("After Copy implementation:\n\t",java_members)